services:
  rl-human-prefs-ui:
    build:
      context: ./rl-human-prefs-ui
      args:
        - HOST_UID=$HOST_UID
        - HOST_GID=$HOST_GID
    ports:
      - "8080:8080"
    user: "$HOST_UID:$HOST_GID"
    volumes:
      - ./rl-human-prefs-ui:/rl-human-prefs-ui
      - /rl-human-prefs-ui/node_modules # not used